### ISSUE TITLE
Backend not working 

### ISSUE THREAD

**Issue by mohd-aquib-razi-7853** [kamlesh-Sahani/ultra-uber-full-stack#1]
I have clone your project.  I follow all your instruction given in your readme file . The only home page is open in frontend , but when I start backend the file get crashed 
![image_2024-12-22_164231750](https://github.com/user-attachments/assets/da3b14e1-c256-4138-82ed-ea0d9668d2e6)

this error come to backend 

And your link [App](https://ultra-uber.vercel.app) is also not working

**Comment by kamlesh-Sahani** [comment]
thanks **aquib** for feedback , 
okay i resolve this as soon as possible
